-- MySQL Script generated by MySQL Workbench
-- Mon Apr 15 00:44:09 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SAMPLE09
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SAMPLE09
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SAMPLE09` DEFAULT CHARACTER SET utf8 ;
USE `SAMPLE09` ;

-- -----------------------------------------------------
-- Table `SAMPLE09`.`PUBLISHER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAMPLE09`.`PUBLISHER` (
  `Name` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `Phone` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`Name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAMPLE09`.`BOOK`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAMPLE09`.`BOOK` (
  `BookId` INT NOT NULL,
  `Title` VARCHAR(45) NOT NULL,
  `PublisherName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`BookId`),
  INDEX `PublisherName_idx` (`PublisherName` ASC),
  CONSTRAINT `Book_PublisherName`
    FOREIGN KEY (`PublisherName`)
    REFERENCES `SAMPLE09`.`PUBLISHER` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAMPLE09`.`BOOK_AUTHORS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAMPLE09`.`BOOK_AUTHORS` (
  `BookId` INT NOT NULL,
  `AuthorName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`BookId`, `AuthorName`),
  CONSTRAINT `Book_Authors_BookId`
    FOREIGN KEY (`BookId`)
    REFERENCES `SAMPLE09`.`BOOK` (`BookId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAMPLE09`.`LIBRARY_BRANCH`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAMPLE09`.`LIBRARY_BRANCH` (
  `BranchId` INT NOT NULL,
  `BranchName` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`BranchId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAMPLE09`.`BOOK_COPIES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAMPLE09`.`BOOK_COPIES` (
  `BookId` INT NOT NULL,
  `BranchId` INT NOT NULL,
  `No_Of_Copies` INT NOT NULL,
  PRIMARY KEY (`BookId`, `BranchId`),
  INDEX `Book_Copies_BranchId_idx` (`BranchId` ASC),
  CONSTRAINT `Book_Copies_BookId`
    FOREIGN KEY (`BookId`)
    REFERENCES `SAMPLE09`.`BOOK` (`BookId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Book_Copies_BranchId`
    FOREIGN KEY (`BranchId`)
    REFERENCES `SAMPLE09`.`LIBRARY_BRANCH` (`BranchId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAMPLE09`.`BORROWER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAMPLE09`.`BORROWER` (
  `CardNo` VARCHAR(16) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `Phone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CardNo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAMPLE09`.`BOOK_LOANS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAMPLE09`.`BOOK_LOANS` (
  `BookId` INT NOT NULL,
  `BranchId` INT NOT NULL,
  `CardNo` VARCHAR(16) NOT NULL,
  `DateOut` DATE NOT NULL,
  `DueDate` DATE NOT NULL,
  PRIMARY KEY (`BookId`, `BranchId`, `CardNo`),
  INDEX `Book_Loans_BranchId_idx` (`BranchId` ASC),
  INDEX `Book_Loans_CardNo_idx` (`CardNo` ASC),
  CONSTRAINT `Book_Loans_BookId`
    FOREIGN KEY (`BookId`)
    REFERENCES `SAMPLE09`.`BOOK` (`BookId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Book_Loans_BranchId`
    FOREIGN KEY (`BranchId`)
    REFERENCES `SAMPLE09`.`LIBRARY_BRANCH` (`BranchId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Book_Loans_CardNo`
    FOREIGN KEY (`CardNo`)
    REFERENCES `SAMPLE09`.`BORROWER` (`CardNo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
